#!/usr/bin/env Rscript
## A few functions to supplement those already in this package.
## URL: github.com/sahilseth/funr
#### -----------------------


## One may define their own functions here
## or load default packages they use quite often
## for example load devtools, knitr etc.

## chmod ugo+rx inst/scripts/funr

dev_text="
Usage: devtools <function> [arguments]
  check           check a package
  install         install a package from source
  install_github  install a github package
  build           build a package

Please use 'devtools -h <function>' to obtain further information about the usage.
"

library(funr)
library(devtools, quietly = TRUE, verbose = FALSE, warn.conflicts = FALSE)

out = funr(commandArgs(trailingOnly = TRUE), help_text = dev_text)


## Use: print(out$value), if you want the exact output
## OR use render_funr(out), to render them in a pretty manner
## Render the output in a nice manner
render_funr(out)
